### ISSUE TITLE
Generated application not working. Might be related to `grunt ts` task.

### ISSUE THREAD

**Issue by amaurymedeiros** [angular-fullstack/generator-angular-fullstack#1552]
I just tried to start a fullstack app. When I run it using `grunt serve`, I see nothing but a blank screen. I can see three similar errors in the console:

```
Uncaught Error: [$injector:nomod] Module 'pidgeotApp.auth' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Uncaught Error: [$injector:nomod] Module 'pidgeotApp.admin' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Uncaught Error: [$injector:unpr] Unknown provider: authInterceptorProvider <- authInterceptor <- $http <- $templateFactory <- $view <- $state
```

I concluded the module files weren't being generated, so I analyzed the `grunt serve` logs and noticed something weird with the `ts` task. Then I ran it separately. There are a lot of errors, as you can see below.

```
$ grunt ts
Running "ts:client" (ts) task
Compiling...
### Fast Compile >>client/app/account/account.ts
### Fast Compile >>client/app/account/login/login.controller.ts
### Fast Compile >>client/app/account/settings/settings.controller.ts
### Fast Compile >>client/app/account/signup/signup.controller.ts
### Fast Compile >>client/app/admin/admin.controller.ts
### Fast Compile >>client/app/admin/admin.module.ts
### Fast Compile >>client/app/admin/admin.router.ts
### Fast Compile >>client/app/app.ts
### Fast Compile >>client/app/main/main.controller.ts
### Fast Compile >>client/app/main/main.ts
### Fast Compile >>client/components/auth/auth.module.ts
### Fast Compile >>client/components/auth/auth.service.ts
### Fast Compile >>client/components/auth/interceptor.service.ts
### Fast Compile >>client/components/auth/router.decorator.ts
### Fast Compile >>client/components/auth/user.service.ts
### Fast Compile >>client/components/footer/footer.directive.ts
### Fast Compile >>client/components/modal/modal.service.ts
### Fast Compile >>client/components/mongoose-error/mongoose-error.directive.ts
### Fast Compile >>client/components/navbar/navbar.controller.ts
### Fast Compile >>client/components/navbar/navbar.directive.ts
### Fast Compile >>client/components/ui-router/ui-router.mock.ts
### Fast Compile >>client/components/util/util.module.ts
### Fast Compile >>client/components/util/util.service.ts
### Fast Compile >>client/typings/angularjs/angular.d.ts
### Fast Compile >>client/typings/jquery/jquery.d.ts
### Fast Compile >>client/typings/lodash/lodash.d.ts
### Fast Compile >>client/typings/socket.io-client/socket.io-client.d.ts
### Fast Compile >>client/typings/tsd.d.ts
Using tsc v1.7.5
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(5,10): error TS2339: Property 'user' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(6,10): error TS2339: Property 'errors' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(7,10): error TS2339: Property 'submitted' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(9,10): error TS2339: Property 'Auth' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(10,10): error TS2339: Property '$state' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(14,10): error TS2339: Property 'submitted' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(17,12): error TS2339: Property 'Auth' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(18,21): error TS2339: Property 'user' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(19,24): error TS2339: Property 'user' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(23,14): error TS2339: Property '$state' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/login/login.controller.ts(26,14): error TS2339: Property 'errors' does not exist on type 'LoginController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(5,10): error TS2339: Property 'errors' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(6,10): error TS2339: Property 'submitted' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(8,10): error TS2339: Property 'Auth' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(12,10): error TS2339: Property 'submitted' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(15,12): error TS2339: Property 'Auth' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(15,37): error TS2339: Property 'user' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(15,60): error TS2339: Property 'user' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(17,16): error TS2339: Property 'message' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(21,16): error TS2339: Property 'errors' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/settings/settings.controller.ts(22,16): error TS2339: Property 'message' does not exist on type 'SettingsController'.
/Users/amaury/dev/pidgeot/client/app/account/signup/signup.controller.ts(11,10): error TS2339: Property 'Auth' does not exist on type 'SignupController'.
/Users/amaury/dev/pidgeot/client/app/account/signup/signup.controller.ts(12,10): error TS2339: Property '$state' does not exist on type 'SignupController'.
/Users/amaury/dev/pidgeot/client/app/account/signup/signup.controller.ts(19,12): error TS2339: Property 'Auth' does not exist on type 'SignupController'.
/Users/amaury/dev/pidgeot/client/app/account/signup/signup.controller.ts(20,25): error TS2339: Property 'name' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/app/account/signup/signup.controller.ts(21,26): error TS2339: Property 'email' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/app/account/signup/signup.controller.ts(22,29): error TS2339: Property 'password' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/app/account/signup/signup.controller.ts(26,14): error TS2339: Property '$state' does not exist on type 'SignupController'.
/Users/amaury/dev/pidgeot/client/app/admin/admin.controller.ts(8,10): error TS2339: Property 'users' does not exist on type 'AdminController'.
/Users/amaury/dev/pidgeot/client/app/admin/admin.controller.ts(13,10): error TS2339: Property 'users' does not exist on type 'AdminController'.
/Users/amaury/dev/pidgeot/client/app/admin/admin.controller.ts(13,28): error TS2339: Property 'users' does not exist on type 'AdminController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(8,10): error TS2339: Property '$http' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(9,10): error TS2339: Property 'awesomeThings' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(12,12): error TS2339: Property 'awesomeThings' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(17,14): error TS2339: Property 'newThing' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(18,12): error TS2339: Property '$http' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(18,51): error TS2339: Property 'newThing' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(19,12): error TS2339: Property 'newThing' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.ts(24,10): error TS2339: Property '$http' does not exist on type 'MainController'.
/Users/amaury/dev/pidgeot/client/components/auth/auth.service.ts(31,30): error TS2339: Property '$promise' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/components/auth/auth.service.ts(81,52): error TS2339: Property '_id' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/components/auth/auth.service.ts(104,21): error TS2339: Property '$promise' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/components/auth/auth.service.ts(149,36): error TS2339: Property 'role' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/components/mongoose-error/mongoose-error.directive.ts(12,45): error TS2339: Property '$setValidity' does not exist on type '{}'.
/Users/amaury/dev/pidgeot/client/components/navbar/navbar.controller.ts(14,10): error TS2339: Property 'isLoggedIn' does not exist on type 'NavbarController'.
/Users/amaury/dev/pidgeot/client/components/navbar/navbar.controller.ts(15,10): error TS2339: Property 'isAdmin' does not exist on type 'NavbarController'.
/Users/amaury/dev/pidgeot/client/components/navbar/navbar.controller.ts(16,10): error TS2339: Property 'getCurrentUser' does not exist on type 'NavbarController'.

>> 47 non-emit-preventing type warnings
>> Type errors only.

TypeScript compilation complete: 1.65s for 29 TypeScript files.

Running "ts:client_test" (ts) task
Compiling...
### Fast Compile >>client/app/main/main.controller.spec.ts
### Fast Compile >>client/components/ui-router/ui-router.mock.ts
### Fast Compile >>client/test_typings/angular-protractor/angular-protractor.d.ts
### Fast Compile >>client/test_typings/assertion-error/assertion-error.d.ts
### Fast Compile >>client/test_typings/chai/chai.d.ts
### Fast Compile >>client/test_typings/mocha/mocha.d.ts
### Fast Compile >>client/test_typings/selenium-webdriver/selenium-webdriver.d.ts
### Fast Compile >>client/test_typings/sinon-chai/sinon-chai.d.ts
### Fast Compile >>client/test_typings/sinon/sinon.d.ts
### Fast Compile >>client/test_typings/tsd.d.ts
Using tsc v1.7.5
/Users/amaury/dev/pidgeot/client/app/main/main.controller.spec.ts(6,14): error TS2304: Cannot find name 'module'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.spec.ts(7,14): error TS2304: Cannot find name 'module'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.spec.ts(15,14): error TS2304: Cannot find name 'inject'.
/Users/amaury/dev/pidgeot/client/app/main/main.controller.spec.ts(29,5): error TS2304: Cannot find name 'expect'.
/Users/amaury/dev/pidgeot/client/components/ui-router/ui-router.mock.ts(3,1): error TS2304: Cannot find name 'angular'.
/Users/amaury/dev/pidgeot/client/components/ui-router/ui-router.mock.ts(4,1): error TS2304: Cannot find name 'angular'.

>> 6 non-emit-preventing type warnings
>> Type errors only.

TypeScript compilation complete: 1.40s for 11 TypeScript files.

Done, without errors.
```

Any idea on what can be causing the problem? It's a newly created app and I already tried to remove `node_modules` and run `npm install` again. Have no clue what to try next.

**Comment by Awk34** [comment]
You'll notice that the TypeScript compiler states that we got `Type errors only.`. This means that all the code is valid, there are just errors with types. You'll also note that there aren't any types declared in the code. This is what causes those type errors.

As for the module errors, we need to make sure that the order of files is app, modules, and then any other JS/TS.

**Comment by amaurymedeiros** [comment]
This is how the `body` of `index.html` looks like (the generated one). Trying to change the import other causes other errors.

``` html
<body ng-app="pidgeotApp">
    <!--[if lt IE 7]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Add your site or application content here -->
    <div ui-view=""></div>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-XXXXX-X');
      ga('send', 'pageview');
    </script>

    <!--[if lt IE 9]>
    <script src="bower_components/es5-shim/es5-shim.js"></script>
    <script src="bower_components/json3/lib/json3.min.js"></script>
    <![endif]-->
    <!-- build:js({client,node_modules}) app/vendor.js -->
      <!-- bower:js -->
      <script src="bower_components/jquery/dist/jquery.js"></script>
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-resource/angular-resource.js"></script>
      <script src="bower_components/angular-cookies/angular-cookies.js"></script>
      <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
      <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
      <script src="bower_components/angular-validation-match/dist/angular-validation-match.min.js"></script>
      <!-- endbower -->
    <!-- endbuild -->
    <!-- build:js({.tmp,client}) app/app.js -->
      <script src="app/app.js"></script>
      <!-- injector:js -->
      <script src="components/auth/interceptor.service.js"></script>
      <script src="app/account/account.js"></script>
      <script src="app/account/settings/settings.controller.js"></script>
      <script src="app/account/signup/signup.controller.js"></script>
      <script src="app/admin/admin.controller.js"></script>
      <script src="app/admin/admin.module.js"></script>
      <script src="app/admin/admin.router.js"></script>
      <script src="app/main/main.controller.js"></script>
      <script src="app/main/main.js"></script>
      <script src="components/auth/auth.module.js"></script>
      <script src="components/auth/auth.service.js"></script>
      <script src="app/account/login/login.controller.js"></script>
      <script src="components/auth/router.decorator.js"></script>
      <script src="components/auth/user.service.js"></script>
      <script src="components/footer/footer.directive.js"></script>
      <script src="components/modal/modal.service.js"></script>
      <script src="components/mongoose-error/mongoose-error.directive.js"></script>
      <script src="components/navbar/navbar.controller.js"></script>
      <script src="components/navbar/navbar.directive.js"></script>
      <script src="components/util/util.module.js"></script>
      <script src="components/util/util.service.js"></script>
      <script src="app/app.constant.js"></script>
      <!-- endinjector -->
    <!-- endbuild -->
  </body>
```

**Comment by Awk34** [comment]
yeah, the `*.module.js` files need to be right after `app.js`

**Comment by amaurymedeiros** [comment]
Thanks! There is only one error left after I changed it:

`angular.js:4487 Uncaught Error: [$injector:unpr] Unknown provider: authInterceptorProvider <- authInterceptor <- $http <- $templateFactory <- $view <- $state`

`index.html` looks like this now:
```html
<!-- build:js({.tmp,client}) app/app.js -->
      <script src="app/app.js"></script>
      <script src="app/admin/admin.module.js"></script>
      <script src="components/auth/auth.module.js"></script>
      <script src="components/util/util.module.js"></script>
      <!-- injector:js -->
      <script src="components/auth/interceptor.service.js"></script>
      <script src="app/account/account.js"></script>
      <script src="app/account/settings/settings.controller.js"></script>
      <script src="app/account/signup/signup.controller.js"></script>
      <script src="app/admin/admin.controller.js"></script>
      <script src="app/admin/admin.module.js"></script>
      <script src="app/admin/admin.router.js"></script>
      <script src="app/main/main.controller.js"></script>
      <script src="app/main/main.js"></script>
      <script src="components/auth/auth.module.js"></script>
      <script src="components/auth/auth.service.js"></script>
      <script src="app/account/login/login.controller.js"></script>
      <script src="components/auth/router.decorator.js"></script>
      <script src="components/auth/user.service.js"></script>
      <script src="components/footer/footer.directive.js"></script>
      <script src="components/modal/modal.service.js"></script>
      <script src="components/mongoose-error/mongoose-error.directive.js"></script>
      <script src="components/navbar/navbar.controller.js"></script>
      <script src="components/navbar/navbar.directive.js"></script>
      <script src="components/util/util.module.js"></script>
      <script src="components/util/util.service.js"></script>
      <script src="app/app.constant.js"></script>
      <!-- endinjector -->
    <!-- endbuild -->
```

**Comment by amaurymedeiros** [comment]
Actually, I copied instead of cut. It's  working now, thanks!

**Comment by amaurymedeiros** [comment]
Modifying `injector.scripts.files` in `Gruntfile.js` to also ignore *.module when running `injector` task did the trick.

```javascript
files: {
          '<%= yeoman.client %>/index.html': [
               [
                 '<%= yeoman.client %>/{app,components}/**/!(*.spec|*.mock|*.module).ts',
                 '<%= yeoman.client %>/app/app.constant.js',
                 '!{.tmp,<%= yeoman.client %>}/app/app.{js,ts}'
               ]
            ]
        }
```

**Comment by fdfandrade** [comment]
Replacing this "var module = /\.module\.js$/;" by this "var module = /[\w/]+.module.ts$/;" in my Gruntfile.js worked for me!

**Comment by andershagebakken** [comment]
None of the above tricks did it for me. All I get now is "Module 'angular20App.auth' is not available!" a lot of times in the console.

The index.html now looks like this: 
` 
      <script src="app/app.js"></script>
      
      <script src="components/auth/router.decorator.js"></script>
      <script src="app/account/account.js"></script>
      <script src="app/account/settings/settings.controller.js"></script>
      <script src="app/account/signup/signup.controller.js"></script>
      <script src="app/admin/admin.controller.js"></script>
      <script src="app/admin/admin.router.js"></script>
      <script src="app/main/main.controller.js"></script>
      <script src="app/main/main.js"></script>
      <script src="components/auth/auth.service.js"></script>
      <script src="components/auth/interceptor.service.js"></script>
      <script src="app/account/login/login.controller.js"></script>
      <script src="components/auth/user.service.js"></script>
      <script src="components/footer/footer.directive.js"></script>
      <script src="components/modal/modal.service.js"></script>
      <script src="components/mongoose-error/mongoose-error.directive.js"></script>
      <script src="components/navbar/navbar.controller.js"></script>
      <script src="components/navbar/navbar.directive.js"></script>
      <script src="components/socket/socket.service.js"></script>
      <script src="components/util/util.service.js"></script>
      <script src="app/app.constant.js"></script>
      
    `

Is it correct?

**Comment by liliya0artyuh** [comment]
fdfandrade trick worked for me... thanks! 
"Replacing this "var module = /.module.js$/;" by this "var module = /[\w/]+.module.ts$/;" in my Gruntfile.js "

**Comment by marcomafessolli** [comment]
+1

**Comment by Awk34** [comment]
I think I see the problem here. The assumption was that the transform function runs before the sort function, which I now don't believe. Changing the sorter to accept either .ts or .js files for the module regex should fix it: `var module = /\.module\.{js,ts}$/;`.

**Comment by s-rajeev** [comment]
I think the full & final fix would be as below
`var module =/\.module\.(js|ts)$/;` in the `sort` function 
**&** allowing injection of either .ts or .js files
`'<%= yeoman.client %>/{app,components}/**/!(*.spec|*.mock).{js,ts}',` 
(this is needed because if you create a new route using the generator then it creates .js files and not .ts files, so either we fix the generator, or, allow injection of .js files)

**Comment by aabm00** [comment]
Hi.

I have created a couple of projects to test how work the new generator, one with the master branch (angular 1.4.x) and other with the canary (angular 1.5.x), and I get the problem mentioned in both,
As mentioned above in this post I have edited the Gruntfile,js changing this two lines

- var module = /\.module\.js$/; --> var module =/\.module\.(js|ts)$/;
- '<%= yeoman.client %>/{app,components}/**/!(*.spec|*.mock).ts', --> '<%= yeoman.client %>/{app,components}/**/!(*.spec|*.mock).{js,ts}',

Now I still can see the message but with the users registered in the app:

> > The delete user and user index api routes are restricted to users with the 'admin' role.
> 
> Test User
> test@example.com
> Admin
> admin@example.com

The problem  is that I can not delete or do anything with users. So I understand that with these changes the problem is partially solved. isn't it?

Thanks

**Comment by aabm00** [comment]
Hi.

I have created a new project with the new version 3.5.0 of the generator with the same configuration of my above message:
**_TypeScript, HTML, CSS, uiRoute, Yes, BootStrap, UIBootStrap, Mongoose (MongoDB), auth (Google, Facebook, Twitter), socket.io, Grunt, Jasmine_**

And I still have the same problem about deleting or doing anything with users.

So, I suposse that the problem isn't still solved in the version 3.5. Am I right?
