### ISSUE TITLE
Wiredep:client, Unhandled 'error' event

### ISSUE THREAD

**Issue by MaximilianLloyd** [angular-fullstack/generator-angular-fullstack#1946]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.4
Node | 6.2.0
npm | 4.0.0
Operating System | Windows 10
wiredep |

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | N

The following happened after i decided to install the monospaced/angular-qrcode bower module. The wiredep module inside the task `wiredep:client` started to throw a bunch errors:
```
[22:52:23] Finished 'lint:scripts:client' after 5.84 s
[22:52:23] Finished 'lint:scripts' after 5.84 s
[22:52:23] Starting 'wiredep:client'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
  at fromObject (buffer.js:287:9)
  at Function.Buffer.from (buffer.js:133:10)
  at new Buffer (buffer.js:112:17)
  at DestroyableTransform._transform (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\wiredep\wiredep.js:135:23)
  at DestroyableTransform.Transform._read (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\wiredep\node_modules\readable-stream\lib\_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\wiredep\node_modules\readable-stream\lib\_stream_transform.js:172:12)
  at doWrite (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\wiredep\node_modules\readable-stream\lib\_stream_writable.js:237:10)
  at writeOrBuffer (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\wiredep\node_modules\readable-stream\lib\_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\wiredep\node_modules\readable-stream\lib\_stream_writable.js:194:11)
  at write (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  at flow (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
  at emitNone (events.js:86:13)
  at DestroyableTransform.emit (events.js:185:7)
  at emitReadable_ (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
  at emitReadable (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
  at readableAddChunk (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
  at afterTransform (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
  at TransformState.afterTransform (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
  at DestroyableTransform.Transform._read (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:12)
  at doWrite (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:237:10)
  at writeOrBuffer (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:194:11)
  at write (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  at flow (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
  at emitNone (events.js:86:13)
  at DestroyableTransform.emit (events.js:185:7)
  at emitReadable_ (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
  at emitReadable (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
  at readableAddChunk (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
  at afterTransform (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
  at TransformState.afterTransform (C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
  at C:\Users\maxll\Desktop\Projects\Gobble\node_modules\vinyl-fs\lib\src\getContents\bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:439:3)

```

**Comment by MaximilianLloyd** [comment]
I actually solved it. I must have cancelled gulp while it was injecting everything, which resulted in the entire HTML document being empty.

**Comment by jdmagic21** [comment]
@MaximilianLloyd  Could you explain what you mean by saying you "cancelled gulp while it was injecting everything". Can you show us an example of what this looks like?

**Comment by Awk34** [comment]
@jdmagic21 sounds like he `CTRL+C`ed while it was running

**Comment by MaximilianLloyd** [comment]
@Awk34 Yeah.

**Comment by gabrielsr** [comment]
$ git checkout client/index.html 

fixed this issue for me.

**Comment by 55sketch** [comment]
Have also had this issue when Gulp fails in the build process - for example if there's a missing dependency or something. Both my SCSS and HTML files were completely stripped out

**Comment by vladyn** [comment]
I have same issue, while adding some tasks to my gulpfile this suddenly came. First I fixed the index.html and it was ok on first run, but now whatever state of the gulpfile and index file this error persists and breaks  ym tasks. 

this is my __wiredep__ that fails


`gulp.task('wiredep', () => {
    gulp.src('index.html')
      .pipe($.filter(file => file.stat && file.stat.size))
      .pipe(wiredep({
          ignorePath: /^(\.\.\/)+/
      }))

    gulp.src('*.html')
      .pipe(wiredep({
          exclude: ['bootstrap-sass'],
          ignorePath: /^(\.\.\/)*\.\./
      }))
      .pipe(gulp.dest('./'));
});
`

my index file is not empty. 
and this is the error 

`[17:02:15] Starting 'wiredep'...
[17:02:15] Finished 'wiredep' after 9.14 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
`

**Comment by almgwary** [comment]
Problem due to empty html file
